server:
  port: ${port:8088}

spring:
  application:
    name: microservice-zuul-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST:http://localhost:8762/eureka/}    # 指定注册中心的地址
  instance:
    preferIpAddress: true

# 下面整个树都非必须，如果不配置，将默认使用 http://GATEWAY:GATEWAY_PORT/想要访问的Eureka服务id的小写/** 路由到：http://想要访问的Eureka服务id的小写:该服务端口/**
zuul:
  routes:
    ignored-services: '*'          # 需要忽视的服务(配置后将不会被路由)
    consumer:                                               # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
      path: /consumer/**                                    # 想要映射到的路径
      service-id: microservice-consumer            # Eureka中的serviceId
 

 