---
spring:
  profiles: node1                                 # 指定profile=peer1
server:
  port: 8761
eureka:
  instance:
    hostname: node1                               # 指定当profile=peer1时，主机名
  client:
    serviceUrl:
      defaultZone: http://node2:8762/eureka/      # 将自己注册到peer2这个Eureka上面去

---
spring:
  profiles: node2
server:
  port: 8762
eureka:
  instance:
    hostname: node2
  client:
    serviceUrl:
      defaultZone: http://node1:8761/eureka/