server:
  port: ${port:8000}
  use-forward-headers: true
  tomcat:
    protocol-header: X-FORWARDED-PROTO
    remote-ip-header: X-FORWARDED-FOR
    port-header: X-Forwarded-Port
    max-threads: 100
spring:
  aop:
    auto: true
    proxy-target-class: true
  application:
    name: microservice-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

    
    initSize: 20
    minIdle: 20
    maxActive: 100
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8212/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true
 

 