server:
  port: ${port:8081}

spring:
  application:
    name: microservice-consumer
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.216.43:3306/springboot?characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true
    username: zls
    password: hz123456
    initSize: 20
    minIdle: 20
    maxActive: 100


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_LIST:http://localhost:8762/eureka/}    # 指定注册中心的地址
  instance:
    preferIpAddress: true
 

 